### ISSUE TITLE
Issue on code

### ISSUE THREAD

**Issue by MourIdri** [Paradoxis/StegCracker#12]
Just followed you tuto and go the issue 

```
stegcracker frame34.png

Traceback (most recent call last):
  File "/usr/local/bin/stegcracker", line 7, in <module>
    from stegcracker.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/stegcracker/__main__.py", line 27
    log(f'StegCracker {__version__} - ({__url__})',)
                                                 ^
SyntaxError: invalid syntax
```

**Comment by Paradoxis** [comment]
It appears you're using Python 3.5 from the stack trace, not 3.6 as stated in the README:

> The program requires Python 3.6 and the steghide binary to be installed. 

It might be that you installed the program with the wrong `pip` binary, try:

```
$ pip3 uninstall stegcracker
$ python3.6 -m pip install -U stegcracker
```
